OS: OSX
osx_image: xcode11.2
language: swift
scripts: xcodebuild clean build test -workspace data-preservation.xcworkspace -scheme "CI" -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
